logging:
  level:
    root: INFO

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/fastsns
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  session:
    store-type: redis

#  datasource:
#    url: "jdbc:mysql://localhost:3306/fastsns"
#    username: ${DATASOURCE_USERNAME}
#    password: ${DATASOURCE_PASSWORD}
#
  data:
    redis:
      host: ${DATA_REDIS_HOST}
      port: ${DATA_REDIS_PORT}

#  jpa:
#    show-sql: true
#    properties:
#      format_sql: true
#      dialect: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
